name: MySignEdit
main: com.skyost.mysignedit.MySignEdit
version: 0.4.2
author: Skyost
commands:
 signedit:
  aliases: [mysignedit, sign-edit, my-sign-edit, mysign-edit, my-signedit, mse, se]
  description: Edit a sign.
permissions:
 se.edit:
  default: op
  description: Allows you to edit your signs.
